### ISSUE TITLE
Doesn’t seem to like this one commit

### ISSUE THREAD

**Issue by rileyjshaw** [uniphil/commit--blog#37]
I’ve tried to blog commit 0065325b42759a67cc72cbad73c5f1d97bdf2857 from [rileyjshaw/rileyjshaw.github.io](https://github.com/rileyjshaw/rileyjshaw.github.io) a few times, but the page hangs on an infinite load. Maybe it doesn’t like the 🔐 emoji?

**Comment by rileyjshaw** [comment]
It also hangs on e7dafd9f5407c87ea2928b7a1173de884528e27a, which doesn’t have an emoji but is super long?

**Comment by uniphil** [comment]
oof 😞 my initial attempts to move this toward git instead of depending on the github api caused this. the git protocol isn't made for grabbing commit data by hash directly, so the first attempt just cloned the whole repo, which _did_ come in under the 30-second timeout wire for some big-ish repositories i checked... but i missed the most important one!

i'm going to bring back the github-api version as default for now, and put the new heavyweight-but-not-github option as an optional alternative.

**Comment by rileyjshaw** [comment]
oh no, I'm sorry for my way too huge repo :'( thank you for looking into this, I love commit--blog so much

(pssst https://github.com/sponsors)

**Comment by uniphil** [comment]
should be working again now -- https://uniphil.commit--blog.com/rileyjshaw/rileyjshaw.github.io/0065325b42759a67cc72cbad73c5f1d97bdf2857

**Comment by uniphil** [comment]
i forgot that it lets you post blogs from any commit it can access. which, actually, i hope this doesn't break it when you try to blog it.

**Comment by rileyjshaw** [comment]
That was so fast, thank you!! Just tried it out, and it works again.

ps cool!
⬇️⬇️⬇️
<img width="663" alt="image" src="https://user-images.githubusercontent.com/1840854/110228096-482bae00-7eb3-11eb-8886-a6c99802074e.png">
⬆️⬆️⬆️
I'll try this with a smaller repo next time 😅

**Comment by rileyjshaw** [comment]
> i forgot that it lets you post blogs from any commit it can access. which, actually, i hope this doesn't break it when you try to blog it.

😂 thief! I can’t blog that one now, as far as I can tell.

**Comment by uniphil** [comment]
muah ha ha 😈 (i un-blogged it, so you hopefully can take it back 😄)

but yay for it working again! lots of ways to fix the pure-git problems, but none of them are quick as it turns out. https://youtu.be/xnzsf0pO33k?t=171
